"""create_company_master

Revision ID: 12f486433126
Revises: 49ecd2820bdd
Create Date: 2026-01-17 23:39:31.182483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f486433126'
down_revision: Union[str, Sequence[str], None] = '49ecd2820bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_forwarder_forwarderaddr'), 'forwarder', type_='foreignkey')
    op.drop_constraint(op.f('fk_forwarder_branchaddr'), 'forwarder', type_='foreignkey')
    op.create_foreign_key(None, 'forwarder', 'masteraddr', ['forwarder_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'forwarder', 'masteraddr', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('masteraddr', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masteraddr', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'forwarder', type_='foreignkey')
    op.drop_constraint(None, 'forwarder', type_='foreignkey')
    op.create_foreign_key(op.f('fk_forwarder_branchaddr'), 'forwarder', 'masteraddr', ['branch_id'], ['id'])
    op.create_foreign_key(op.f('fk_forwarder_forwarderaddr'), 'forwarder', 'masteraddr', ['forwarder_id'], ['id'])
    # ### end Alembic commands ###
