"""create_po_schedule_line fix

Revision ID: 55271a5f594c
Revises: a56828451eaa
Create Date: 2026-01-22 16:55:50.713018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55271a5f594c'
down_revision: Union[str, Sequence[str], None] = 'a56828451eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('po_schedule_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('shipment_header_id', sa.Integer(), nullable=True),
    sa.Column('schedule_number', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['po_item_id'], ['po_item.id'], ),
    sa.ForeignKeyConstraint(['shipment_header_id'], ['shipment_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_company_code'), 'company_master', type_='unique')
    op.drop_index(op.f('ix_company_master_company_code'), table_name='company_master')
    op.create_index(op.f('ix_company_master_company_code'), 'company_master', ['company_code'], unique=True)
    op.alter_column('container_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('cost_component_lookup', 'is_tax',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cost_component_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('cost_component_lookup_component_code_key'), 'cost_component_lookup', type_='unique')
    op.create_index(op.f('ix_cost_component_lookup_component_code'), 'cost_component_lookup', ['component_code'], unique=True)
    op.alter_column('document_type_lookup', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('document_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('document_type_lookup_type_code_key'), 'document_type_lookup', type_='unique')
    op.create_index(op.f('ix_document_type_lookup_type_code'), 'document_type_lookup', ['type_code'], unique=True)
    op.alter_column('milestone_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('partner_master', sa.Column('payment_terms_code', sa.String(length=20), nullable=True))
    op.add_column('partner_master', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('partner_master_partner_identifier_key'), 'partner_master', type_='unique')
    op.create_index(op.f('ix_partner_master_partner_identifier'), 'partner_master', ['partner_identifier'], unique=True)
    op.create_unique_constraint(None, 'partner_master', ['tax_registration_id'])
    op.drop_constraint(op.f('partner_role_lookup_role_code_key'), 'partner_role_lookup', type_='unique')
    op.create_index(op.f('ix_partner_role_lookup_role_code'), 'partner_role_lookup', ['role_code'], unique=True)
    op.drop_constraint(op.f('po_header_po_number_key'), 'po_header', type_='unique')
    op.create_index(op.f('ix_po_header_po_number'), 'po_header', ['po_number'], unique=True)
    op.add_column('po_item', sa.Column('split_count', sa.Integer(), nullable=False))
    op.alter_column('po_item_status_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('po_status_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('po_status_lookup_status_code_key'), 'po_status_lookup', type_='unique')
    op.create_index(op.f('ix_po_status_lookup_status_code'), 'po_status_lookup', ['status_code'], unique=True)
    op.alter_column('po_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('po_type_lookup_type_code_key'), 'po_type_lookup', type_='unique')
    op.create_index(op.f('ix_po_type_lookup_type_code'), 'po_type_lookup', ['type_code'], unique=True)
    op.drop_constraint(op.f('pricing_type_lookup_type_code_key'), 'pricing_type_lookup', type_='unique')
    op.create_index(op.f('ix_pricing_type_lookup_type_code'), 'pricing_type_lookup', ['type_code'], unique=True)
    op.drop_constraint(op.f('product_master_sku_identifier_key'), 'product_master', type_='unique')
    op.create_index(op.f('ix_product_master_hs_code'), 'product_master', ['hs_code'], unique=False)
    op.create_index(op.f('ix_product_master_sku_identifier'), 'product_master', ['sku_identifier'], unique=True)
    op.alter_column('product_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('purchase_org_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('purchase_org_lookup_org_code_key'), 'purchase_org_lookup', type_='unique')
    op.create_index(op.f('ix_purchase_org_lookup_org_code'), 'purchase_org_lookup', ['org_code'], unique=True)
    op.drop_constraint(op.f('shipment_header_shipment_number_key'), 'shipment_header', type_='unique')
    op.create_index(op.f('ix_shipment_header_shipment_number'), 'shipment_header', ['shipment_number'], unique=True)
    op.add_column('shipment_item', sa.Column('po_schedule_line_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_shipment_item_header_id'), table_name='shipment_item')
    op.drop_constraint(op.f('fk_shipment_item_po_line'), 'shipment_item', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_item', 'po_schedule_line', ['po_schedule_line_id'], ['id'])
    op.drop_column('shipment_item', 'po_item_id')
    op.add_column('shipment_milestone', sa.Column('notes', sa.String(length=255), nullable=True))
    op.alter_column('shipment_status_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('shipment_status_lookup_status_code_key'), 'shipment_status_lookup', type_='unique')
    op.create_index(op.f('ix_shipment_status_lookup_status_code'), 'shipment_status_lookup', ['status_code'], unique=True)
    op.create_index(op.f('ix_system_qualifier_code'), 'system_qualifier', ['code'], unique=False)
    op.alter_column('text_type_lookup', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('text_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('text_type_lookup_text_type_code_key'), 'text_type_lookup', type_='unique')
    op.create_index(op.f('ix_text_type_lookup_text_type_code'), 'text_type_lookup', ['text_type_code'], unique=True)
    op.alter_column('transport_mode_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('uom_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uom_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('transport_mode_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_text_type_lookup_text_type_code'), table_name='text_type_lookup')
    op.create_unique_constraint(op.f('text_type_lookup_text_type_code_key'), 'text_type_lookup', ['text_type_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('text_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('text_type_lookup', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_system_qualifier_code'), table_name='system_qualifier')
    op.drop_index(op.f('ix_shipment_status_lookup_status_code'), table_name='shipment_status_lookup')
    op.create_unique_constraint(op.f('shipment_status_lookup_status_code_key'), 'shipment_status_lookup', ['status_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('shipment_status_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('shipment_milestone', 'notes')
    op.add_column('shipment_item', sa.Column('po_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shipment_item', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shipment_item_po_line'), 'shipment_item', 'po_item', ['po_item_id'], ['id'])
    op.create_index(op.f('ix_shipment_item_header_id'), 'shipment_item', ['shipment_header_id'], unique=False)
    op.drop_column('shipment_item', 'po_schedule_line_id')
    op.drop_index(op.f('ix_shipment_header_shipment_number'), table_name='shipment_header')
    op.create_unique_constraint(op.f('shipment_header_shipment_number_key'), 'shipment_header', ['shipment_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_purchase_org_lookup_org_code'), table_name='purchase_org_lookup')
    op.create_unique_constraint(op.f('purchase_org_lookup_org_code_key'), 'purchase_org_lookup', ['org_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('purchase_org_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('product_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_product_master_sku_identifier'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_hs_code'), table_name='product_master')
    op.create_unique_constraint(op.f('product_master_sku_identifier_key'), 'product_master', ['sku_identifier'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pricing_type_lookup_type_code'), table_name='pricing_type_lookup')
    op.create_unique_constraint(op.f('pricing_type_lookup_type_code_key'), 'pricing_type_lookup', ['type_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_po_type_lookup_type_code'), table_name='po_type_lookup')
    op.create_unique_constraint(op.f('po_type_lookup_type_code_key'), 'po_type_lookup', ['type_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('po_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_po_status_lookup_status_code'), table_name='po_status_lookup')
    op.create_unique_constraint(op.f('po_status_lookup_status_code_key'), 'po_status_lookup', ['status_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('po_status_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('po_item_status_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('po_item', 'split_count')
    op.drop_index(op.f('ix_po_header_po_number'), table_name='po_header')
    op.create_unique_constraint(op.f('po_header_po_number_key'), 'po_header', ['po_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_partner_role_lookup_role_code'), table_name='partner_role_lookup')
    op.create_unique_constraint(op.f('partner_role_lookup_role_code_key'), 'partner_role_lookup', ['role_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'partner_master', type_='unique')
    op.drop_index(op.f('ix_partner_master_partner_identifier'), table_name='partner_master')
    op.create_unique_constraint(op.f('partner_master_partner_identifier_key'), 'partner_master', ['partner_identifier'], postgresql_nulls_not_distinct=False)
    op.drop_column('partner_master', 'is_verified')
    op.drop_column('partner_master', 'payment_terms_code')
    op.alter_column('milestone_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_document_type_lookup_type_code'), table_name='document_type_lookup')
    op.create_unique_constraint(op.f('document_type_lookup_type_code_key'), 'document_type_lookup', ['type_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('document_type_lookup', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_cost_component_lookup_component_code'), table_name='cost_component_lookup')
    op.create_unique_constraint(op.f('cost_component_lookup_component_code_key'), 'cost_component_lookup', ['component_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('cost_component_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cost_component_lookup', 'is_tax',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('container_type_lookup', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_company_master_company_code'), table_name='company_master')
    op.create_index(op.f('ix_company_master_company_code'), 'company_master', ['company_code'], unique=False)
    op.create_unique_constraint(op.f('uq_company_code'), 'company_master', ['company_code'], postgresql_nulls_not_distinct=False)
    op.drop_table('po_schedule_line')
    # ### end Alembic commands ###
