"""add incoterm lookup and schedule shipments

Revision ID: a38ac7b6c111
Revises: a1b2c3d4e5f6
Create Date: 2026-02-04 00:39:53.601549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38ac7b6c111'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS incoterm_lookup (
            id SERIAL PRIMARY KEY,
            incoterm VARCHAR(20) NOT NULL,
            incoterm_description VARCHAR(255),
            is_active BOOLEAN NOT NULL
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ix_incoterm_lookup_incoterm ON incoterm_lookup (incoterm)"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS ship_type_lookup (
            id SERIAL PRIMARY KEY,
            type_code VARCHAR(20) NOT NULL,
            type_name VARCHAR(100) NOT NULL,
            description VARCHAR(255),
            is_active BOOLEAN NOT NULL,
            created_at TIMESTAMP DEFAULT now() NOT NULL
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ix_ship_type_lookup_type_code ON ship_type_lookup (type_code)"
    )
    op.drop_index(op.f('ix_number_range_lookup'), table_name='sys_number_ranges')
    op.drop_table('sys_number_ranges')
    op.drop_constraint(op.f('currency_lookup_currency_code_key'), 'currency_lookup', type_='unique')
    op.drop_index(op.f('ix_currency_lookup_code'), table_name='currency_lookup')
    op.create_index(op.f('ix_currency_lookup_currency_code'), 'currency_lookup', ['currency_code'], unique=True)
    op.drop_index(op.f('ix_customer_branch_branch_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_branch_customer_id'), table_name='customer')
    op.create_index(op.f('ix_customer_branch_id'), 'customer', ['branch_id'], unique=False)
    op.create_index(op.f('ix_customer_customer_id'), 'customer', ['customer_id'], unique=False)
    op.drop_constraint(op.f('fk_customer_branch_branch_id'), 'customer', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_branch_customer_id'), 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'partner_master', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'customer', 'partner_master', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_customer_forwarder_customer_id'), table_name='customer_forwarder_map')
    op.drop_index(op.f('ix_customer_forwarder_forwarder_id'), table_name='customer_forwarder_map')
    op.create_index(op.f('ix_customer_forwarder_map_customer_id'), 'customer_forwarder_map', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_forwarder_map_forwarder_id'), 'customer_forwarder_map', ['forwarder_id'], unique=False)
    op.drop_constraint(op.f('fk_customer_forwarder_customer_id'), 'customer_forwarder_map', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_forwarder_forwarder_id'), 'customer_forwarder_map', type_='foreignkey')
    op.create_foreign_key(None, 'customer_forwarder_map', 'partner_master', ['forwarder_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'customer_forwarder_map', 'customer_master', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('customer_master', 'validity_to',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text("'9999-12-31'::date"))
    op.drop_constraint(op.f('customer_master_customer_identifier_key'), 'customer_master', type_='unique')
    op.create_index(op.f('ix_customer_master_customer_identifier'), 'customer_master', ['customer_identifier'], unique=True)
    op.drop_constraint(op.f('customer_role_lookup_role_code_key'), 'customer_role_lookup', type_='unique')
    op.create_index(op.f('ix_customer_role_lookup_role_code'), 'customer_role_lookup', ['role_code'], unique=True)
    op.drop_constraint(op.f('forwarder_forwarder_id_fkey'), 'forwarder', type_='foreignkey')
    op.drop_constraint(op.f('forwarder_branch_id_fkey'), 'forwarder', type_='foreignkey')
    op.create_foreign_key(None, 'forwarder', 'partner_master', ['forwarder_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'forwarder', 'partner_master', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.execute("ALTER TABLE po_schedule_line ADD COLUMN IF NOT EXISTS shipments INTEGER")
    op.add_column('shipment_header', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shipment_header', 'ship_type_lookup', ['type_id'], ['id'])
    op.drop_index(op.f('ix_workflow_rules_lookup'), table_name='sys_workflow_rules')
    op.drop_index(op.f('ix_user_customer_customer_id'), table_name='user_customer_map')
    op.drop_index(op.f('ix_user_customer_email'), table_name='user_customer_map')
    op.create_index(op.f('ix_user_customer_map_customer_id'), 'user_customer_map', ['customer_id'], unique=False)
    op.create_index(op.f('ix_user_customer_map_user_email'), 'user_customer_map', ['user_email'], unique=False)
    op.drop_constraint(op.f('fk_user_customer_email'), 'user_customer_map', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_customer_customer_id'), 'user_customer_map', type_='foreignkey')
    op.create_foreign_key(None, 'user_customer_map', 'customer_master', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'user_customer_map', 'users', ['user_email'], ['email'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_user_partner_email'), table_name='user_partner_map')
    op.drop_index(op.f('ix_user_partner_partner_id'), table_name='user_partner_map')
    op.create_index(op.f('ix_user_partner_map_partner_id'), 'user_partner_map', ['partner_id'], unique=False)
    op.create_index(op.f('ix_user_partner_map_user_email'), 'user_partner_map', ['user_email'], unique=False)
    op.drop_constraint(op.f('fk_user_partner_partner_id'), 'user_partner_map', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_partner_email'), 'user_partner_map', type_='foreignkey')
    op.create_foreign_key(None, 'user_partner_map', 'partner_master', ['partner_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'user_partner_map', 'users', ['user_email'], ['email'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_partner_map', type_='foreignkey')
    op.drop_constraint(None, 'user_partner_map', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_partner_email'), 'user_partner_map', 'users', ['user_email'], ['email'])
    op.create_foreign_key(op.f('fk_user_partner_partner_id'), 'user_partner_map', 'partner_master', ['partner_id'], ['id'])
    op.drop_index(op.f('ix_user_partner_map_user_email'), table_name='user_partner_map')
    op.drop_index(op.f('ix_user_partner_map_partner_id'), table_name='user_partner_map')
    op.create_index(op.f('ix_user_partner_partner_id'), 'user_partner_map', ['partner_id'], unique=False)
    op.create_index(op.f('ix_user_partner_email'), 'user_partner_map', ['user_email'], unique=False)
    op.drop_constraint(None, 'user_customer_map', type_='foreignkey')
    op.drop_constraint(None, 'user_customer_map', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_customer_customer_id'), 'user_customer_map', 'customer_master', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_customer_email'), 'user_customer_map', 'users', ['user_email'], ['email'])
    op.drop_index(op.f('ix_user_customer_map_user_email'), table_name='user_customer_map')
    op.drop_index(op.f('ix_user_customer_map_customer_id'), table_name='user_customer_map')
    op.create_index(op.f('ix_user_customer_email'), 'user_customer_map', ['user_email'], unique=False)
    op.create_index(op.f('ix_user_customer_customer_id'), 'user_customer_map', ['customer_id'], unique=False)
    op.create_index(op.f('ix_workflow_rules_lookup'), 'sys_workflow_rules', ['doc_category', 'doc_type_id', 'state_code'], unique=False)
    op.drop_constraint(None, 'shipment_header', type_='foreignkey')
    op.drop_column('shipment_header', 'type_id')
    op.drop_column('po_schedule_line', 'shipments')
    op.drop_constraint(None, 'forwarder', type_='foreignkey')
    op.drop_constraint(None, 'forwarder', type_='foreignkey')
    op.create_foreign_key(op.f('forwarder_branch_id_fkey'), 'forwarder', 'masteraddr', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('forwarder_forwarder_id_fkey'), 'forwarder', 'masteraddr', ['forwarder_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_customer_role_lookup_role_code'), table_name='customer_role_lookup')
    op.create_unique_constraint(op.f('customer_role_lookup_role_code_key'), 'customer_role_lookup', ['role_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_customer_master_customer_identifier'), table_name='customer_master')
    op.create_unique_constraint(op.f('customer_master_customer_identifier_key'), 'customer_master', ['customer_identifier'], postgresql_nulls_not_distinct=False)
    op.alter_column('customer_master', 'validity_to',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text("'9999-12-31'::date"))
    op.drop_constraint(None, 'customer_forwarder_map', type_='foreignkey')
    op.drop_constraint(None, 'customer_forwarder_map', type_='foreignkey')
    op.create_foreign_key(op.f('fk_customer_forwarder_forwarder_id'), 'customer_forwarder_map', 'partner_master', ['forwarder_id'], ['id'])
    op.create_foreign_key(op.f('fk_customer_forwarder_customer_id'), 'customer_forwarder_map', 'customer_master', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_customer_forwarder_map_forwarder_id'), table_name='customer_forwarder_map')
    op.drop_index(op.f('ix_customer_forwarder_map_customer_id'), table_name='customer_forwarder_map')
    op.create_index(op.f('ix_customer_forwarder_forwarder_id'), 'customer_forwarder_map', ['forwarder_id'], unique=False)
    op.create_index(op.f('ix_customer_forwarder_customer_id'), 'customer_forwarder_map', ['customer_id'], unique=False)
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key(op.f('fk_customer_branch_customer_id'), 'customer', 'partner_master', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('fk_customer_branch_branch_id'), 'customer', 'partner_master', ['branch_id'], ['id'])
    op.drop_index(op.f('ix_customer_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_branch_id'), table_name='customer')
    op.create_index(op.f('ix_customer_branch_customer_id'), 'customer', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_branch_branch_id'), 'customer', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_currency_lookup_currency_code'), table_name='currency_lookup')
    op.create_index(op.f('ix_currency_lookup_code'), 'currency_lookup', ['currency_code'], unique=False)
    op.create_unique_constraint(op.f('currency_lookup_currency_code_key'), 'currency_lookup', ['currency_code'], postgresql_nulls_not_distinct=False)
    op.create_table('sys_number_ranges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('doc_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('padding', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('include_year', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_number_ranges_pkey')),
    sa.UniqueConstraint('doc_category', 'doc_type_id', name=op.f('uix_category_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_number_range_lookup'), 'sys_number_ranges', ['doc_category', 'doc_type_id'], unique=False)
    op.drop_index(op.f('ix_ship_type_lookup_type_code'), table_name='ship_type_lookup')
    op.drop_table('ship_type_lookup')
    op.drop_index(op.f('ix_incoterm_lookup_incoterm'), table_name='incoterm_lookup')
    op.drop_table('incoterm_lookup')
    # ### end Alembic commands ###
