from app.models.customer_master import CustomerMaster
from app.models.customer_role import CustomerRole
from app.models.masteraddr import MasterAddr

CUSTOMER_MASTER_REPORT_CONFIG = {
    "report_id": "customer_master",
    "base_model": CustomerMaster,
    "fields": {
        "customer_code": {
            "path": CustomerMaster.customer_identifier,
            "label": "Customer Code",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "search",
            "sortable": True,
        },
        "customer_role": {
            "path": CustomerRole.role_name,
            "label": "Customer Role",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [CustomerRole],
        },
        "legal_name": {
            "path": CustomerMaster.legal_name,
            "label": "Legal Name",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "search",
            "sortable": True,
        },
        "trade_name": {
            "path": CustomerMaster.trade_name,
            "label": "Trade Name",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "search",
        },
        "tax_id": {
            "path": CustomerMaster.tax_registration_id,
            "label": "Tax Registration ID",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "search",
        },
        "payment_terms": {
            "path": CustomerMaster.payment_terms_code,
            "label": "Payment Terms",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "search",
        },
        "currency": {
            "path": CustomerMaster.preferred_currency,
            "label": "Currency",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "search",
        },
        "is_active": {
            "path": CustomerMaster.is_active,
            "label": "Active",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "select",
            "options": [True, False],
        },
        "created_at": {
            "path": CustomerMaster.created_at,
            "label": "Created At",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "date_range",
        },
        "updated_at": {
            "path": CustomerMaster.updated_at,
            "label": "Updated At",
            "group": "Customer",
            "is_filterable": True,
            "filter_type": "date_range",
        },
        "addr_type": {
            "path": MasterAddr.addr_type,
            "label": "Address Type",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "street": {
            "path": MasterAddr.street,
            "label": "Street",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "house_no": {
            "path": MasterAddr.housenumber,
            "label": "House No.",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "city": {
            "path": MasterAddr.city,
            "label": "City",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "zip": {
            "path": MasterAddr.zip,
            "label": "ZIP",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "country": {
            "path": MasterAddr.country,
            "label": "Country",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "email": {
            "path": MasterAddr.emailid,
            "label": "Email",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "phone1": {
            "path": MasterAddr.phone1,
            "label": "Phone 1",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "phone2": {
            "path": MasterAddr.phone2,
            "label": "Phone 2",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
    },
    "default_columns": [
        "customer_code",
        "legal_name",
        "customer_role",
        "city",
        "country",
        "email",
        "phone1",
        "is_active",
    ],
    "default_sort": "customer_code",
}
