from app.models.partner_master import PartnerMaster
from app.models.partner_role import PartnerRole
from app.models.masteraddr import MasterAddr

PARTNER_MASTER_REPORT_CONFIG = {
    "report_id": "partner_master",
    "base_model": PartnerMaster,
    "fields": {
        "partner_code": {
            "path": PartnerMaster.partner_identifier,
            "label": "Partner Code",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "search",
            "sortable": True,
        },
        "partner_role": {
            "path": PartnerRole.role_name,
            "label": "Partner Role",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [PartnerRole],
        },
        "legal_name": {
            "path": PartnerMaster.legal_name,
            "label": "Legal Name",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "search",
            "sortable": True,
        },
        "trade_name": {
            "path": PartnerMaster.trade_name,
            "label": "Trade Name",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "search",
        },
        "tax_id": {
            "path": PartnerMaster.tax_registration_id,
            "label": "Tax Registration ID",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "search",
        },
        "payment_terms": {
            "path": PartnerMaster.payment_terms_code,
            "label": "Payment Terms",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "search",
        },
        "currency": {
            "path": PartnerMaster.preferred_currency,
            "label": "Currency",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "search",
        },
        "is_active": {
            "path": PartnerMaster.is_active,
            "label": "Active",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "select",
        },
        "is_verified": {
            "path": PartnerMaster.is_verified,
            "label": "Verified",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "select",
        },
        "created_at": {
            "path": PartnerMaster.created_at,
            "label": "Created At",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "date_range",
        },
        "updated_at": {
            "path": PartnerMaster.updated_at,
            "label": "Updated At",
            "group": "Partner",
            "is_filterable": True,
            "filter_type": "date_range",
        },
        "addr_type": {
            "path": MasterAddr.addr_type,
            "label": "Address Type",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "street": {
            "path": MasterAddr.street,
            "label": "Street",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "house_no": {
            "path": MasterAddr.housenumber,
            "label": "House No.",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "city": {
            "path": MasterAddr.city,
            "label": "City",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "zip": {
            "path": MasterAddr.zip,
            "label": "ZIP",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "country": {
            "path": MasterAddr.country,
            "label": "Country",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "email": {
            "path": MasterAddr.emailid,
            "label": "Email",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "phone1": {
            "path": MasterAddr.phone1,
            "label": "Phone 1",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
        "phone2": {
            "path": MasterAddr.phone2,
            "label": "Phone 2",
            "group": "Address",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [MasterAddr],
        },
    },
    "default_columns": [
        "partner_code",
        "legal_name",
        "partner_role",
        "city",
        "country",
        "email",
        "phone1",
        "is_active",
    ],
}
