from app.models.shipment import ShipmentHeader, ShipmentItem
from app.models.po_schedule_line import POScheduleLine


ShipmentHeaderJoin = (ShipmentHeader, ShipmentItem.shipment_header_id == ShipmentHeader.id)


SHIPMENT_REPORT_CONFIG = {
    "report_id": "shipment_report",
    "base_model": ShipmentItem,
    "default_columns": [
        "shipment_number",
        "shipment_item_number",
        "predecessor_doc",
        "predecessor_item_no",
        "po_number",
        "schedule_line_no",
        "shipped_qty",
        "package_id",
        "gross_weight",
        "external_reference",
        "master_bill_lading",
        "estimated_departure",
        "estimated_arrival",
        "actual_arrival",
        "created_at",
        "updated_at",
        "created_by",
        "last_changed_by",
    ],
    "fields": {
        # --- SHIPMENT ITEM ---
        "shipment_item_id": {
            "path": ShipmentItem.id,
            "label": "Shipment Item ID",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric",
            "hidden": True,
        },
        "shipment_header_id": {
            "path": ShipmentItem.shipment_header_id,
            "label": "Shipment Header ID",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric",
            "hidden": True,
        },
        "shipment_item_number": {
            "path": ShipmentItem.shipment_item_number,
            "label": "Shipment Item #",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric",
        },
        "po_schedule_line_id": {
            "path": ShipmentItem.po_schedule_line_id,
            "label": "Schedule Line ID",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric",
            "hidden": True,
        },
        "po_item_id": {
            "path": ShipmentItem.po_item_id,
            "label": "PO Item ID",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric",
            "hidden": True,
        },
        "po_number": {
            "path": ShipmentItem.po_number,
            "label": "PO Number",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "search",
        },
        "predecessor_doc": {
            "path": ShipmentItem.predecessor_doc,
            "label": "Predecessor Doc",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "search",
        },
        "predecessor_item_no": {
            "path": ShipmentItem.predecessor_item_no,
            "label": "Predecessor Item",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric",
        },
        "schedule_line_no": {
            "path": POScheduleLine.schedule_number,
            "label": "Schedule Line #",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric",
            "join_path": [(POScheduleLine, ShipmentItem.po_schedule_line_id == POScheduleLine.id)],
        },
        "shipped_qty": {
            "path": ShipmentItem.shipped_qty,
            "label": "Shipped Qty",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric_range",
        },
        "package_id": {
            "path": ShipmentItem.package_id,
            "label": "Package ID",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "search",
        },
        "gross_weight": {
            "path": ShipmentItem.gross_weight,
            "label": "Gross Weight",
            "group": "Shipment Item",
            "is_filterable": True,
            "filter_type": "numeric_range",
        },

        # --- SHIPMENT HEADER ---
        "shipment_number": {
            "path": ShipmentHeader.shipment_number,
            "label": "Shipment Number",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [ShipmentHeaderJoin],
        },
        "external_reference": {
            "path": ShipmentHeader.external_reference,
            "label": "External Reference",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [ShipmentHeaderJoin],
        },
        "type_id": {
            "path": ShipmentHeader.type_id,
            "label": "Shipment Type",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "numeric",
            "join_path": [ShipmentHeaderJoin],
            "hidden": True,
        },
        "status_id": {
            "path": ShipmentHeader.status_id,
            "label": "Shipment Status",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "numeric",
            "join_path": [ShipmentHeaderJoin],
            "hidden": True,
        },
        "mode_id": {
            "path": ShipmentHeader.mode_id,
            "label": "Transport Mode",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "numeric",
            "join_path": [ShipmentHeaderJoin],
            "hidden": True,
        },
        "carrier_id": {
            "path": ShipmentHeader.carrier_id,
            "label": "Carrier",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "numeric",
            "join_path": [ShipmentHeaderJoin],
            "hidden": True,
        },
        "pol_port_id": {
            "path": ShipmentHeader.pol_port_id,
            "label": "POL Port",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "numeric",
            "join_path": [ShipmentHeaderJoin],
            "hidden": True,
        },
        "pod_port_id": {
            "path": ShipmentHeader.pod_port_id,
            "label": "POD Port",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "numeric",
            "join_path": [ShipmentHeaderJoin],
            "hidden": True,
        },
        "master_bill_lading": {
            "path": ShipmentHeader.master_bill_lading,
            "label": "Master B/L",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [ShipmentHeaderJoin],
        },
        "estimated_departure": {
            "path": ShipmentHeader.estimated_departure,
            "label": "ETD",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "date_range",
            "join_path": [ShipmentHeaderJoin],
        },
        "estimated_arrival": {
            "path": ShipmentHeader.estimated_arrival,
            "label": "ETA",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "date_range",
            "join_path": [ShipmentHeaderJoin],
        },
        "actual_arrival": {
            "path": ShipmentHeader.actual_arrival,
            "label": "Actual Arrival",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "date_range",
            "join_path": [ShipmentHeaderJoin],
        },
        "created_at": {
            "path": ShipmentHeader.created_at,
            "label": "Created At",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "date_range",
            "join_path": [ShipmentHeaderJoin],
        },
        "updated_at": {
            "path": ShipmentHeader.updated_at,
            "label": "Updated At",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "date_range",
            "join_path": [ShipmentHeaderJoin],
        },
        "created_by": {
            "path": ShipmentHeader.created_by,
            "label": "Created By",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [ShipmentHeaderJoin],
        },
        "last_changed_by": {
            "path": ShipmentHeader.last_changed_by,
            "label": "Last Changed By",
            "group": "Shipment Header",
            "is_filterable": True,
            "filter_type": "search",
            "join_path": [ShipmentHeaderJoin],
        },
    },
}
